SELECT * FROM VJEZBE.ZAPOSLENIK;
DELETE FROM VJEZBE.KLIJENT WHERE IME = 'Ana';

CREATE TABLE VJEZBE.TVRTKA(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
NAZIV VARCHAR(50) NOT NULL,
OIB VARCHAR(11) NOT NULL,
PRIMARY KEY (ID)
);

INSERT INTO VJEZBE.TVRTKA (NAZIV, OIB) VALUES ('Turbo softver', '61233549876');

CREATE TABLE VJEZBE.KLIJENT(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
OIB VARCHAR(11) NOT NULL,
PREZIME VARCHAR(25) NOT NULL,
IME VARCHAR(25) NOT NULL,
TELEFON VARCHAR(25) NOT NULL,
EMAIL VARCHAR(25) NOT NULL,
DATUM_RODJENJA DATE NOT NULL,
PRIMARY KEY(ID)
);

INSERT INTO VJEZBE.KLIJENT (OIB, PREZIME, IME, TELEFON, EMAIL, DATUM_RODJENJA) VALUES
('98765432123', 'Periæ', 'Pero', '098777666', 'peric.pero@java.com', '1996-05-01');
INSERT INTO VJEZBE.KLIJENT (OIB, PREZIME, IME, TELEFON, EMAIL, DATUM_RODJENJA) VALUES
('76545678909', 'Iviæ', 'Ivo', '091654321', 'ivic.ivo@eclipse.com', '1998-06-05');
INSERT INTO VJEZBE.KLIJENT (OIB, PREZIME, IME, TELEFON, EMAIL, DATUM_RODJENJA) VALUES
('12345678903', 'Horvat', 'Marko', '098654321', 'marko.horvat@test.hr', '1998-08-13');

CREATE TABLE VJEZBE.TVRTKA_KLIJENT(
TVRTKA_ID INT NOT NULL,
KLIJENT_ID INT NOT NULL,
PRIMARY KEY(TVRTKA_ID, KLIJENT_ID),
FOREIGN KEY(TVRTKA_ID) REFERENCES VJEZBE.TVRTKA(ID),
FOREIGN KEY(KLIJENT_ID) REFERENCES VJEZBE.KLIJENT(ID)
);

INSERT INTO VJEZBE.TVRTKA_KLIJENT VALUES (1, 1);
INSERT INTO VJEZBE.TVRTKA_KLIJENT VALUES (1, 2);
INSERT INTO VJEZBE.TVRTKA_KLIJENT VALUES (1, 3);

CREATE TABLE VJEZBE.ZAPOSLENIK(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
KORISNICKO_IME VARCHAR(25) NOT NULL,
PREZIME VARCHAR(25) NOT NULL,
IME VARCHAR(25) NOT NULL,
SIFRA VARCHAR(25) NOT NULL,
PRIMARY KEY (ID)
);

INSERT INTO VJEZBE.ZAPOSLENIK(KORISNICKO_IME, PREZIME, IME, SIFRA) VALUES 
('ihorvat','Ivana', 'Horvat', 'ih543');
INSERT INTO VJEZBE.ZAPOSLENIK(KORISNICKO_IME, PREZIME, IME, SIFRA) VALUES
('mkovacevic', 'Martina', 'Kovaèeviæ', 'mk123');

CREATE TABLE VJEZBE.TVRTKA_ZAPOSLENIK(
TVRTKA_ID INT NOT NULL,
ZAPOSLENIK_ID INT NOT NULL,
PRIMARY KEY(TVRTKA_ID, ZAPOSLENIK_ID),
FOREIGN KEY(TVRTKA_ID) REFERENCES VJEZBE.TVRTKA(ID),
FOREIGN KEY(ZAPOSLENIK_ID) REFERENCES VJEZBE.ZAPOSLENIK(ID)
);

INSERT INTO VJEZBE.TVRTKA_ZAPOSLENIK VALUES (1, 1);
INSERT INTO VJEZBE.TVRTKA_ZAPOSLENIK VALUES (1, 2);

CREATE TABLE VJEZBE.KATEGORIJA_ARTIKLA(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
NAZIV VARCHAR(25) NOT NULL,
PRIMARY KEY (ID)
);

INSERT INTO VJEZBE.KATEGORIJA_ARTIKLA(NAZIV) VALUES ('SOFTVER');
INSERT INTO VJEZBE.KATEGORIJA_ARTIKLA(NAZIV) VALUES ('ELEKTROTEHNIKA');
INSERT INTO VJEZBE.KATEGORIJA_ARTIKLA(NAZIV) VALUES ('MEHANIKA');
INSERT INTO VJEZBE.KATEGORIJA_ARTIKLA(NAZIV) VALUES ('OSTALO');

CREATE TABLE VJEZBE.ARTIKL(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
NAZIV VARCHAR(25) NOT NULL,
KATEGORIJA_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY(KATEGORIJA_ID ) REFERENCES  VJEZBE.KATEGORIJA_ARTIKLA(ID )
);

INSERT INTO VJEZBE.ARTIKL (NAZIV, KATEGORIJA_ID) VALUES ('Mobilna aplikacija', 1);
INSERT INTO VJEZBE.ARTIKL (NAZIV, KATEGORIJA_ID) VALUES ('Web aplikacija', 1);
INSERT INTO VJEZBE.ARTIKL (NAZIV, KATEGORIJA_ID) VALUES ('Edukacija', 4);

CREATE TABLE VJEZBE.TVRTKA_ARTIKL(
TVRTKA_ID INT NOT NULL,
ARTIKL_ID INT NOT NULL,
PRIMARY KEY(TVRTKA_ID, ARTIKL_ID),
FOREIGN KEY(TVRTKA_ID) REFERENCES VJEZBE.TVRTKA(ID),
FOREIGN KEY(ARTIKL_ID) REFERENCES VJEZBE.ARTIKL(ID)
);

INSERT INTO VJEZBE.TVRTKA_ARTIKL (TVRTKA_ID, ARTIKL_ID) VALUES (1, 1);
INSERT INTO VJEZBE.TVRTKA_ARTIKL (TVRTKA_ID, ARTIKL_ID) VALUES (1, 2);
INSERT INTO VJEZBE.TVRTKA_ARTIKL (TVRTKA_ID, ARTIKL_ID) VALUES (1, 3);

CREATE TABLE VJEZBE.VRSTA_KOMUNIKACIJE(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
NAZIV VARCHAR(25) NOT NULL,
PRIMARY KEY (ID)
);

INSERT INTO VJEZBE.VRSTA_KOMUNIKACIJE(NAZIV) VALUES ('VERBALNA');
INSERT INTO VJEZBE.VRSTA_KOMUNIKACIJE(NAZIV) VALUES ('PISMENA');
INSERT INTO VJEZBE.VRSTA_KOMUNIKACIJE(NAZIV) VALUES ('ELEKTRONICKA');
INSERT INTO VJEZBE.VRSTA_KOMUNIKACIJE(NAZIV) VALUES ('OSTALO');

CREATE TABLE VJEZBE.ALARM(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
OPIS VARCHAR(250) NOT NULL,
KLIJENT_ID INT NOT NULL,
VRIJEME TIMESTAMP NOT NULL,
AKTIVAN BOOLEAN NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY(KLIJENT_ID) REFERENCES VJEZBE.KLIJENT(ID)
);

CREATE TABLE VJEZBE.KOMUNIKACIJA(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
KLIJENT_ID INT NOT NULL,
ZAPOSLENIK_ID INT NOT NULL,
VRSTA_KOMUNIKACIJE_ID INT NOT NULL,
SADRZAJ VARCHAR(500) NOT NULL,
VRIJEME TIMESTAMP NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY(KLIJENT_ID) REFERENCES VJEZBE.KLIJENT(ID),
FOREIGN KEY(ZAPOSLENIK_ID) REFERENCES VJEZBE.ZAPOSLENIK(ID),
FOREIGN KEY(VRSTA_KOMUNIKACIJE_ID) REFERENCES VJEZBE.VRSTA_KOMUNIKACIJE(ID)
);

CREATE TABLE VJEZBE.VRSTA_USLUGE(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
NAZIV VARCHAR(25) NOT NULL,
PRIMARY KEY (ID)
);

INSERT INTO VJEZBE.VRSTA_USLUGE (NAZIV) VALUES ('PRODAJNA');
INSERT INTO VJEZBE.VRSTA_USLUGE (NAZIV) VALUES ('PRAVNA');
INSERT INTO VJEZBE.VRSTA_USLUGE (NAZIV) VALUES ('OSTALO');

CREATE TABLE VJEZBE.USLUGA(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
OPIS VARCHAR(250) NOT NULL,
KLIJENT_ID INT NOT NULL,
VRSTA_USLUGE_ID INT NOT NULL,
DATUM DATE NOT NULL,
CIJENA DECIMAL(10,2) NOT NULL,
PLACENA BOOLEAN NOT NULL,
OBAVLJENA BOOLEAN NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY(KLIJENT_ID) REFERENCES VJEZBE.KLIJENT(ID),
FOREIGN KEY(VRSTA_USLUGE_ID ) REFERENCES VJEZBE.VRSTA_USLUGE(ID)
);